title: Sami El Alaoui El Abdallaoui
description: Graduate from The University Of Leeds in AI, and from the University Of Sheffield in Bioengineering. Both Russel Group Universities ranked in the Top 100 in the QS World Universities Rankings.
show_downloads: false
theme: jekkll-theme-minimal
